### ISSUE TITLE
Logs Issue

### ISSUE THREAD

**Issue by jsdizon** [mallowlabs/newrelic_tomcat_plugin#1]
Hi Sir,

Sorry for my comment, but i have an issue regarding logs after i start the plugin, I got this error..

[root@tomcat tomcat-0.0.1]# java -jar tomcat-0.0.1.jar
INFO: Using configuration file /opt/newrelic_tomcat_plugin/dist/tomcat-0.0.1/config/newrelic.properties
WARNING: Logging is not currently configured. Please add a config/logging.properties file to enable additional logging.
INFO: New Relic monitor started
Apr 20, 2015 9:52:25 PM org.codefirst.newrelic.plugins.tomcat.TomcatStatus fetch
SEVERE: Server redirected too many  times (20)
java.net.ProtocolException: Server redirected too many  times (20)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1636)
    at java.net.URLConnection.getContent(URLConnection.java:748)
    at org.codefirst.newrelic.plugins.tomcat.TomcatStatus.fetch(Unknown Source)
    at org.codefirst.newrelic.plugins.tomcat.Tomcat.pollCycle(Unknown Source)
    at com.newrelic.metrics.publish.Runner$PollAgentsRunnable.run(Unknown Source)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
Apr 20, 2015 9:53:25 PM org.codefirst.newrelic.plugins.tomcat.TomcatStatus fetch

Many thanks!

**Comment by jsdizon** [comment]
Hi @mallowlabs 

Solved this issue, sorry. I forgot to uncomment the users on the tomcat-users.xml.
But i have an issue again, it doesn't show any data on the new relic plugin dashboard, it only shows the Tomcat tab but there's no data. Can you please advise? Thanks!

**Comment by jsdizon** [comment]
Hi @mallowlabs 

Fixed this. Sorry, i understand that the plugin is not fully developed. But the plugin is cool. Hope you can finish it. Thanks!
